config/routes.rb
require 'sidekiq/web' # require the web UI

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Flipper::UI.app(Flipper) => '/flipper'
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Prettytodo::Engine => '/prettytodo' if Rails.env.development?

  get 'groups/page=:page' => 'groups#index'
  get 'people/page=:page' => 'people#index'
  get 'transfers/page=:page' => 'transfers#index'

  get 'groups/group_people/:group_id/page=:page' => 'groups#group_people'
  get 'groups/affiliated_groups/:group_id/page=:page' => 'groups#affiliated_groups'
  get 'groups/money_summary/:group_id' => 'groups#money_summary'
  get 'groups/:id/reload' => 'groups#reload'

  get 'people/:id/network_graph' => 'inertia#network_graph_person'
  get 'groups/:id/network_graph' => 'inertia#network_graph_group'

  get 'search' => 'search#index'
  get '/home/suggestions' => 'home#suggestions'

  get '/post_to_socials' => 'home#post_to_socials'              # Random
  get '/people/:id/post_to_socials' => 'people#post_to_socials' # Person

  get '/people/:id/reload' => 'people#reload'
  get '/tradingnames/:id' => 'trading_names#show'

  resources :transfers
  resources :groups
  resources :people

  # todo: remove these
  resources :lazy_load_groups
  resources :lazy_load_people
  resources :lazy_load_transfers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/home/todo' => 'home#todo'
  get '/todo' => 'home#todo'

  get '/home/index' => 'home#index'
  get '/about' => 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'search#index'

  # # Add a custom POST route for Memberships
  post '/admin/memberships/general_upload_action', to: 'admin/memberships#general_upload_action', as: :general_upload_action_admin_memberships
  post '/admin/memberships/ministries_upload_action', to: 'admin/memberships#ministries_upload_action', as: :ministries_upload_action_admin_memberships
  post '/admin/groups/perform_merge', to: 'admin/groups#perform_merge'
  post '/admin/people/ingest_linkedin', to: 'admin/people#ingest_linkedin'
end

app/models/person.rb
class Person < ApplicationRecord
  include TransferMethods
  include NodeMethods
  include CachedMethods

  include PgSearch::Model
  multisearchable against: [:name]

  lazy_columns :cached_data

  include ActionView::Helpers::NumberHelper

  has_many :trading_names, as: :owner, dependent: :destroy
  has_many :memberships, as: :member, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :positions, through: :memberships

  has_many :outgoing_transfers, class_name: 'Transfer', as: :giver, dependent: :destroy
  has_many :incoming_transfers, class_name: 'Transfer', as: :taker, dependent: :destroy

  accepts_nested_attributes_for :memberships, allow_destroy: true

  scope :nodes_count_expired, -> { where(nodes_count_cached_at: ..7.days.ago).or(where(nodes_count_cached: nil)) }
  scope :nodes_count_soon_expired, -> { where(nodes_count_cached_at: ...7.days.ago).or(where(nodes_count_cached: nil)) }

  validates :name, uniqueness: { case_sensitive: false }

  def nodes
    groups
  end

  def transfers
    # TODO: Potentially useless code
    OpenStruct.new(
      incoming: Transfer.where(taker: self), # always nil. replace with [] ?,
      outgoing: Transfer.where(giver: self, giver_type: 'Person').order(amount: :desc)
    )
  end

  def other_edge_ends
    outgoing_transfers.map(&:taker)
  end

  def is_tag? = false
  def is_group? = false
  def is_person? = true
  def business_number = nil

  # rubocop:disable Style/StringConcatenation # feels nicer in this case
  def tweet_body
    body = <<~SUMMARY.strip
      🔍 #{name}

      👥 Member of #{number_of_groups}
      🔗 Directly connected to #{number_of_direct_contacts} in our database.

      💰 Money Tracker:
      ➡️ Direct transfers: #{direct_transfers}.
      📡 One degree separation: #{first_degree_transfers}
    SUMMARY

    call_to_action = "\n\n" + "See more: https://join-the-dots.info/people/#{id}"
    body += call_to_action if (body.length + call_to_action.length) < 300
    aus_pol_tag = "\n\n" + '#AusPol'
    body += aus_pol_tag if (body.length + aus_pol_tag.length) < 300
    name_to_tag = ' #' + name.downcase.tr(' ', '_')
    body += name_to_tag if (body.length + name_to_tag.length) < 300
    final_sign_off = ' #follow_the_money'
    body += final_sign_off if (body.length + final_sign_off.length) < 300

    body.strip
  end
  # rubocop:enable Style/StringConcatenation

  private

  def direct_friendships
    # PEOPLE, with whom this person has a direct relationship, ie they are both part of the same group.
    # The group must be <= MAX_GROUP_SIZE_TO_FOLLOW, otherwise the relationship is too weak to be considered direct.
    # That constant is used in the BuildQueue service.
    consolidated_descendents_depth(2).filter{|descendent| descendent.klass == 'Person' && descendent.depth == 2}
  end

  def direct_transfers
    # TODO: Potentially Useless Code
    # largely duplicated by code inside node methods
    transfers_in = incoming_transfers.sum(:amount)
    transfers_out = outgoing_transfers.sum(:amount)

    return 'None' if transfers_in.zero? && transfers_out.zero?
    return "Incoming: #{number_to_currency(transfers_in, precision: 0)}" if transfers_out.zero?
    return "Outgoing: #{number_to_currency(transfers_out, precision: 0)}" if transfers_in.zero?

    "Incoming: #{number_to_currency(transfers_in, precision: 0)}, Outgoing: #{number_to_currency(transfers_out, precision: 0)}"
  end

  def first_degree_transfers
    # TODO: cache some of these database calls
    # TODO: Potentially Useless Code
    # largely duplicated by code inside node methods
    transfers = consolidated_transfers(depth: 1).filter { |transfer| transfer.depth == 1 }
    incoming_transfers = transfers.filter { |transfer| transfer.direction == 'incoming' }
    outgoing_transfers = transfers.filter { |transfer| transfer.direction == 'outgoing' }
    OpenStruct.new(
      in: number_to_currency(incoming_transfers.sum(&:amount), precision: 0),
      out: number_to_currency(outgoing_transfers.sum(&:amount), precision: 0)
    )

    return 'None' if incoming_transfers.empty? && outgoing_transfers.empty?
    return "Incoming: #{number_to_currency(incoming_transfers.sum(&:amount), precision: 0)}" if outgoing_transfers.empty?
    return "Outgoing: #{number_to_currency(outgoing_transfers.sum(&:amount), precision: 0)}" if incoming_transfers.empty?

    "Incoming: #{number_to_currency(incoming_transfers.sum(&:amount), precision: 0)}, Outgoing: #{number_to_currency(outgoing_transfers.sum(&:amount), precision: 0)}"
  end

  def number_of_groups
    "#{nodes_count} #{'group'.pluralize(nodes_count)}"
  end

  def number_of_direct_contacts
    "#{direct_friendships.count} #{'person'.pluralize(direct_friendships.count)}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  rate_limit to: Constants::CONTROLLER_RATE_LIMIT, within: 1.minute, with: -> { redirect_to search_path, alert: 'Too many requests, Please try in a minute...' } unless Rails.env.test? || Rails.env.development?

  include Constants

  before_action :set_person, only: %i[ show edit update destroy post_to_socials]
  before_action :set_page, only: %i[ index ]

  def index
    people = Person.order(:name)
                   .limit(page_size)
                   .offset(paginate_offset)
                   .includes([:groups])
                   .to_a

    pages = (Person.count.to_f / page_size).ceil

    render People::IndexView.new(people:, page: @page, pages:)
  end

  def show
    if @person.cache_fresh?
      render People::ShowView.new(person: @person)
    else
      BuildPersonCachedDataJob.perform_async(@person.id)
      render Common::PleaseRefreshLater.new
    end
  end

  def reload
    @person = Person.find(params[:id])
    BuildPersonCachedDataJob.perform_async(@person.id)

    render People::ShowView.new(person: @person.reload)
  end

  def post_to_socials
    message = @person.tweet_body
    BlueskyService.skeet(message)

    render json: { message: message }, status: :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Only allow a list of trusted parameters through. Including nested params for memberships
  def person_params
    params.require(:person).permit(:name, memberships_attributes: [:id, :title, :start_date, :end_date, :_destroy])
  end

  def page_size
    return 250

    @page_size ||= Constants::PAGE_LIMIT
  end

  def set_page
    @page = (params[:page] || 0).to_i
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: @person, url: person_path(@person), method: :patch, class: 'form') do |form| %>
  <!-- Person Attributes -->
  <div class="form-group">
    <div class="row">
      <div class="col-md-3">
        <%= form.label :name, class: 'form-label' %>
      </div>
      <div class="col-md-9">
        <%= form.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>

  <!-- Other person attributes go here -->

  <!-- Memberships Fields -->
  <h2>Edit Existing Memberships</h2>

  <table class="table">
    <thead>
      <tr>
        <th>Group Name</th>

        <th>Start Date</th>
        <th>End Date</th>
        <!-- Add other membership attributes as needed -->
      </tr>
    </thead>
    <tbody>
      <% @person.memberships.each do |membership| %>
        <tr>
          <td><%= membership.group.name %></td>
          <%= form.fields_for :memberships, membership do |membership_form| %>


            <td>
              <div class="form-group">
                <%= membership_form.date_field :start_date, class: 'form-control' %>
              </div>
            </td>

            <td>
              <div class="form-group">
                <%= membership_form.date_field :end_date, class: 'form-control' %>
              </div>
            </td>
            <!-- Add other membership attributes as needed -->
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Add a new membership -->
  <h2>Add a New Membership</h2>
  <%= form.fields_for :memberships, Membership.new, child_index: 'NEW_RECORD' do |membership_form| %>
    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :group_id, 'Group', class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.select :group_id, Group.all.map { |group| [group.name, group.id] }, { prompt: 'Select Group' }, class: 'form-control' %>
        </div>
      </div>
    </div>



    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :start_date, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.date_field :start_date, placeholder: 'Start Date', class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :end_date, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.date_field :end_date, placeholder: 'End Date', class: 'form-control' %>
        </div>
      </div>
    </div>
    <!-- Add other membership attributes as needed -->
  <% end %>

  <!-- Submit Button -->
  <div class="form-actions">
    <%= form.submit 'Update Person and Memberships', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Name:</strong>
    <%= person.name %>
    <ul>
      <% person.groups.each do |group| %>
        <li>
          <%= group.name %>
        </li>
      <% end %>
    </ul>
  </p>

</div>

app/views/people/edit.html.erb
<%= render MenuComponent.new %>

<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>
<hr>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= form_with(model: Person.new, url: people_path, class: 'form') do |form| %>
  <!-- Person Attributes -->
  <div class="form-group">
    <div class="row">
      <div class="col-md-3">
        <%= form.label :name, class: 'form-label' %>
      </div>
      <div class="col-md-9">
        <%= form.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>

  <!-- Other person attributes go here -->

  <!-- Memberships Fields -->
  <h2>Edit Existing Memberships</h2>

  <!-- Existing memberships table goes here -->

  <!-- Add a new membership -->
  <h2>Add a New Membership</h2>
  <%= form.fields_for :memberships, Membership.new, child_index: 'NEW_RECORD' do |membership_form| %>
    <!-- New membership fields go here -->
    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :group_id, 'Group', class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.select :group_id, Group.all.map { |group| [group.name, group.id] }, { prompt: 'Select Group' }, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :title, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.text_field :title, placeholder: 'Title', class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :start_date, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.date_field :start_date, placeholder: 'Start Date', class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :end_date, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.date_field :end_date, placeholder: 'End Date', class: 'form-control' %>
        </div>
      </div>
    </div>
    <!-- Add other membership attributes as needed -->
  <% end %>

  <!-- Submit Button -->
  <div class="form-actions">
    <%= form.submit 'Create Person and Memberships', class: 'btn btn-primary' %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>