config/routes.rb
require 'sidekiq/web' # require the web UI

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Flipper::UI.app(Flipper) => '/flipper'
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Prettytodo::Engine => '/prettytodo' if Rails.env.development?

  get 'groups/page=:page' => 'groups#index'
  get 'people/page=:page' => 'people#index'
  get 'transfers/page=:page' => 'transfers#index'

  get 'groups/group_people/:group_id/page=:page' => 'groups#group_people'
  get 'groups/affiliated_groups/:group_id/page=:page' => 'groups#affiliated_groups'
  get 'groups/money_summary/:group_id' => 'groups#money_summary'
  get 'groups/:id/reload' => 'groups#reload'

  get 'people/:id/network_graph' => 'inertia#network_graph_person'
  get 'groups/:id/network_graph' => 'inertia#network_graph_group'

  get 'search' => 'search#index'
  get '/home/suggestions' => 'home#suggestions'

  get '/post_to_socials' => 'home#post_to_socials'              # Random
  get '/people/:id/post_to_socials' => 'people#post_to_socials' # Person

  get '/people/:id/reload' => 'people#reload'
  get '/tradingnames/:id' => 'trading_names#show'

  resources :transfers
  resources :groups
  resources :people

  # todo: remove these
  resources :lazy_load_groups
  resources :lazy_load_people
  resources :lazy_load_transfers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/home/todo' => 'home#todo'
  get '/todo' => 'home#todo'

  get '/home/index' => 'home#index'
  get '/about' => 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'search#index'

  # # Add a custom POST route for Memberships
  post '/admin/memberships/general_upload_action', to: 'admin/memberships#general_upload_action', as: :general_upload_action_admin_memberships
  post '/admin/memberships/ministries_upload_action', to: 'admin/memberships#ministries_upload_action', as: :ministries_upload_action_admin_memberships
  post '/admin/groups/perform_merge', to: 'admin/groups#perform_merge'
  post '/admin/people/ingest_linkedin', to: 'admin/people#ingest_linkedin'
end

app/models/group.rb
class Group < ApplicationRecord
  include TransferMethods
  include NodeMethods
  include CachedMethods

  include PgSearch::Model
  multisearchable against: [:name]

  lazy_columns :cached_data

  MAJOR_POLITICAL_GROUPS = ['Australian Labor Party', 'Liberal / National Coalition', 'The Greens'].freeze

  NAMES = OpenStruct.new(
            coalition: OpenStruct.new(
              federal: 'The Coalition (Federal)',
              nsw: 'The Coalition (NSW)',
              sa: 'The Coalition (SA)',
              vic: 'The Coalition (VIC)',
              tas: 'The Coalition (TAS)',
              wa: 'The Coalition (WA)',
              act: 'The Coalition (ACT)'
            ),
            liberals: OpenStruct.new(
              federal: 'Liberals (Federal)',
              nsw: 'Liberals (NSW)',
              qld: 'Liberal National Party (QLD)',
              sa: 'Liberals (SA)',
              vic: 'Liberals (VIC)',
              tas: 'Liberals (TAS)',
              wa: 'Liberals (WA)',
              act: 'Liberals (ACT)',
              nt: 'Country Liberal Party (NT)'
            ),
            nationals: OpenStruct.new(
              federal: 'Nationals (Federal)',
              nsw: 'Nationals (NSW)',
              qld: 'Liberal National Party (QLD)',
              sa: 'Nationals (SA)',
              vic: 'Nationals (VIC)',
              tas: 'Nationals (TAS)',
              wa: 'Nationals (WA)',
              act: 'Nationals (ACT)',
              nt: 'Country Liberal Party (NT)'
            ),
            labor: OpenStruct.new(
              federal: 'ALP (Federal)',
              nsw: 'ALP (NSW)',
              qld: 'ALP (QLD)',
              sa: 'ALP (SA)',
              vic: 'ALP (VIC)',
              tas: 'ALP (TAS)',
              wa: 'ALP (WA)',
              act: 'ALP (ACT)',
              nt: 'ALP (NT)'
            ),
            greens: OpenStruct.new(
              federal: 'The Greens (Federal)',
              nsw: 'The Greens (NSW)',
              qld: 'The Greens (QLD)',
              sa: 'The Greens (SA)',
              vic: 'The Greens (VIC)',
              tas: 'The Greens (TAS)',
              wa: 'The Greens (WA)',
              act: 'The Greens (ACT)',
              nt: 'The Greens (NT)'
            )
          )

  has_many :trading_names, as: :owner, dependent: :destroy
  has_many :leadership_websites, dependent: :destroy

  # TODO: memberships are only working on one direction, need to fix this
  # affiliated groups are not being followed from child to parent to other child
  has_many :memberships, dependent: :destroy
  has_many :people, through: :memberships, source: :member, source_type: 'Person'
  has_many :groups, through: :memberships, source: :member, source_type: 'Group' # these are the groups that _belong_ to _this_ group
  # these are a bit weird, hence the transfers method below
  has_many :outgoing_transfers, class_name: 'Transfer', as: :giver, dependent: :destroy
  has_many :incoming_transfers, class_name: 'Transfer', as: :taker, dependent: :destroy

  validates :name, uniqueness: { case_sensitive: false }
  validates :business_number, uniqueness: { case_sensitive: false }, allow_nil: true

  accepts_nested_attributes_for :memberships, allow_destroy: true

  normalizes :business_number, with: ->(bn) { bn.presence }
  normalizes :business_number, with: ->(bn) { bn.presence&.gsub(/\D/, '') }

  # scopes
  scope :major_political_tags, -> do
    where(type: 'Tag').where(name: MAJOR_POLITICAL_GROUPS).order(:name)
  end
  scope :other_tags, -> do
    where(type: 'Tag').where.not(name: MAJOR_POLITICAL_GROUPS).order(:name)
  end

  scope :political_parties, -> do
    where(
      id: Membership.joins(:group)
                    .where(groups: { type: 'Tag', name: MAJOR_POLITICAL_GROUPS })
                    .select(:member_id)
    )
  end

  scope :with_business_number, -> { where.not(business_number: [nil, '']) }

  scope :can_refresh, -> { where(last_refreshed: nil).or(where(last_refreshed: ..6.months.ago)) }

  scope :nodes_count_expired, -> { where(nodes_count_cached_at: ..8.days.ago).or(where(nodes_count_cached: nil)) }
  scope :nodes_count_soon_expired, -> { where(nodes_count_cached_at: ..4.days.ago).or(where(nodes_count_cached: nil)) }

  scope :orphans, -> {
    # Groups with no members and no transfers. They may be children of parent groups
    left_outer_joins(:memberships, :incoming_transfers, :outgoing_transfers)
      .where(memberships: { id: nil })
      .where(incoming_transfers: { id: nil })
      .where(outgoing_transfers: { id: nil })
      .distinct
  }

  # Scope: has at least one person
  scope :with_people, -> {
    joins(:people).distinct
  }
  # Scope: has at least one group (as member)
  scope :with_groups, -> {
    joins(:groups).distinct
  }

  scope :created_since, ->(since) {
    where(created_at: since..Time.current)
  }

  # Scope: groups that are members of the lobbyists tag
  scope :lobbyist_groups, -> {
    lobbyist_tag = Group.lobbyists_tag
    joins("INNER JOIN memberships ON memberships.member_id = groups.id AND memberships.member_type = 'Group'")
      .where('memberships.group_id = ?', lobbyist_tag.id)
      .distinct
  }

  def parent_groups
    Group.joins(:memberships).where(memberships: { member: self, member_type: 'Group' }).where.not(id: self.id)
  end

  def nodes
    people + affiliated_groups
  end

  def affiliated_groups
    parent_groups + groups
  end

  def less_level
    # only called from a disused section in FileIngestor
    # TODO: Potentially useless code
    name.gsub(/(Federal|NSW|VIC|SA|WA|TAS|ACT|NT)/, '')
        .delete('(')
        .delete(')')
        .strip
  end

  def state
    name.match(/(NSW|VIC|QLD|SA|WA|TAS|ACT|NT)/).to_s
  end

  def self.summarise_for(group = nil)
    major_groupings = %i(coalition nationals labor green liberals)
    states = %i[federal nsw vic qld sa wa nt act tas]

    list = major_groupings.map do |major_group|
      states.map do |state|
        NAMES.send(major_group).send(state) if NAMES.send(major_group)
      end
    end

    if group.present?
      list.flatten.compact.uniq - [group.name]
    else
      list.flatten.compact.uniq
    end
  end

  def is_tag?
    type == 'Tag'
  end

  def is_group? = true
  def is_person? = false

  def display_name
    return "#{name} (#{business_number})" if business_number.present?

    name
  end

  def add_to_tag(tag_group: nil, tag_name: nil)
    raise ArgumentError, 'Either tag_group or tag_name must be provided' if tag_group.blank? && tag_name.blank?
    return if self.is_tag?

    tag_group ||= Group.find_or_create_by!(name: tag_name, type: 'Tag')
    Tag::AddGroupToTag.call(tag: tag_group, group: self)
  end

  def self.all_named_parties
    NAMES.to_h.keys.map do |key|
      NAMES.send(key).to_h.values
    end.flatten.uniq
  end

  def self.find_by_name_i(name)
    Group.where('LOWER(name) = ?', name.downcase).first
  end

  def self.lobbyists_tag
    Group.find_by(name: 'Lobbyists')
  end

  def self.client_of_lobbyists_tag
    Group.find_by(name: 'Client of Lobbyists')
  end

  def self.government_department_tag
    Group.find_by(name: 'Government Departments (AU, Federal & State)')
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  rate_limit to: Constants::CONTROLLER_RATE_LIMIT, within: 1.minute, with: -> { redirect_to search_path, alert: 'Too many requests, Please try in a minute...' } # unless Rails.env.test? || Rails.env.development?

  include Constants

  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :set_page, only: %i[ index ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  def index
    groups = Group.order(:name).limit(page_size).offset(paginate_offset).to_a
    pages = (Group.count.to_f / page_size).ceil

    render Groups::IndexView.new(groups:, page: @page, pages:)
  end

  def show
    if @group.cache_fresh?
      render Groups::ShowView.new(group: @group)
    else
      BuildGroupCachedDataJob.perform_async(@group.id)
      render Common::PleaseRefreshLater.new
    end
  end

  def reload
    @group = Group.find(params[:id])
    BuildGroupCachedDataJob.perform_async(@group.id)

    render Groups::ShowView.new(group: @group.reload)
  end

  def affiliated_groups
    @group = Group.find(params[:group_id])
    @page = params[:page].to_i

    render Groups::AffiliatedGroups.new(group: @group)
  end

  def money_summary
    render Common::MoneySummary.new(entity: Group.find(params[:group_id]))
  end

  def group_people
    # This action used to have pagination. TODO: re-add pagination into the new format?
    group = Group.find(params[:group_id])
    page = params[:page].to_i
    pages = (group.people.count.to_f / page_size).ceil

    people = group.cached
                  .direct_connections
                  .filter { |c| c['klass'] == 'Person' }
                  .sort_by { |c| c['name'] }

    #  passing an array of hashes to the view
    render Groups::PeopleTable.new(people:, exclude_group: group, page:, pages:)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  def set_page
    @page = (params[:page] || 0).to_i
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, memberships_attributes: [:id, :title, :start_date, :end_date, :_destroy])
  end

  def update_group(group)
    people_ids = group_params['people_ids'].compact_blank.map(&:to_i)

    people_ids.each do |id|
      person = Person.find(id)
      person.groups << group unless person.groups.include?(group)
    end

    group
  end

  def page_size
    return 250

    @page_size ||= Constants::PAGE_LIMIT
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @group, url: group_path(@group), method: :patch, class: 'form') do |form| %>
  <!-- Group Attributes -->
  <div class="form-group">
    <div class="row">
      <div class="col-md-3">
        <%= form.label :name, class: 'form-label' %>
      </div>
      <div class="col-md-9">
        <%= form.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>

  <!-- Other group attributes go here -->

  <!-- Memberships Fields -->
  <h2>Edit Memberships</h2>

  <table class="table">
    <thead>
      <tr>
        <th>Person Name</th>
        <th>Title</th>
        <th>Start Date</th>
        <th>End Date</th>
        <!-- Add other membership attributes as needed -->
      </tr>
    </thead>
    <tbody>
      <% @group.memberships.each do |membership| %>
        <tr>
          <td><%= membership.person.name %></td>
          <%= form.fields_for :memberships, membership do |membership_form| %>
            <td>
              <div class="form-group">
                <%= membership_form.text_field :title, class: 'form-control' %>
              </div>
            </td>

            <td>
              <div class="form-group">
                <%= membership_form.date_field :start_date, class: 'form-control' %>
              </div>
            </td>

            <td>
              <div class="form-group">
                <%= membership_form.date_field :end_date, class: 'form-control' %>
              </div>
            </td>
            <!-- Add other membership attributes as needed -->
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>



  <!-- Add a new membership -->
  <h2>Add a New Membership</h2>
  <%= form.fields_for :memberships, Membership.new, child_index: 'NEW_RECORD' do |membership_form| %>
    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :person_id, 'Person', class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.select :person_id, Person.all.map { |person| [person.name, person.id] }, { prompt: 'Select Person' }, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :title, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.text_field :title, placeholder: 'Title', class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :start_date, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.date_field :start_date, placeholder: 'Start Date', class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :end_date, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.date_field :end_date, placeholder: 'End Date', class: 'form-control' %>
        </div>
      </div>
    </div>
    <!-- Add other membership attributes as needed -->
  <% end %>

  <!-- Submit Button -->
  <div class="form-actions">
    <%= form.submit 'Update Group and Memberships', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="col-md-4">
  <div class="card" style="width: 18rem;">

    <div class="card-body">
      <%= link_to group.name, group_path(group), class: "btn #{group.name} w-100"  %>
      <p class="card-text">Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah Blah </p>
    </div>
      <% group.people.each do |person| %>
        <div class="list-group-item flex-normal">
          <div>

                        <%= link_to person.name, person_path(person), class: "btn-primary btn #{person.name}"  %>
          </div>
          <div>
          <% person.groups.map(&:name).reject{ |n| n == group.name } .each do |group_name|  %>
            <button class="btn btn-sm <%= group_name %>"><%= group_name %></button>
          <% end %>
          </div>



        </div>
      <% end %>

    </ul>
    <div class="card-body">

    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Groups</h1>

<div class="row", id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
  <% end %>
</div>

<%= link_to "New group", new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= form_with(model: Group.new, url: groups_path, class: 'form') do |form| %>
  <!-- Group Attributes -->
  <div class="form-group">
    <div class="row">
      <div class="col-md-3">
        <%= form.label :name, class: 'form-label' %>
      </div>
      <div class="col-md-9">
        <%= form.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>

  <!-- Other Group attributes go here -->

  <!-- Memberships Fields -->
  <h2>Edit Existing Memberships</h2>

  <!-- Existing memberships table goes here -->

  <!-- Add a new membership -->
  <h2>Add a New Membership</h2>
  <%= form.fields_for :memberships, Membership.new, child_index: 'NEW_RECORD' do |membership_form| %>
    <!-- New membership fields go here -->
    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :person_id, 'Group', class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.select :person_id, Person.all.map { |person| [person.name, person.id] }, { prompt: 'Select Person' }, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :title, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.text_field :title, placeholder: 'Title', class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :start_date, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.date_field :start_date, placeholder: 'Start Date', class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-3">
          <%= membership_form.label :end_date, class: 'form-label' %>
        </div>
        <div class="col-md-9">
          <%= membership_form.date_field :end_date, placeholder: 'End Date', class: 'form-control' %>
        </div>
      </div>
    </div>
    <!-- Add other membership attributes as needed -->
  <% end %>

  <!-- Submit Button -->
  <div class="form-actions">
    <%= form.submit 'Create Group and Memberships', class: 'btn btn-primary' %>
  </div>
<% end %>

<br>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<div>
  <%= render Groups::Heading.new(group: @group) %>
</div>

<div>
  <%= render Groups::MoneySummary.new(group: @group) %>
</div>

<div>
  <%= render Groups::AffiliatedGroups.new(group: @group) %>
</div>

<div>
  <%= render Groups::People.new(group: @group) %>
</div>

<div>
  <%= render TransfersTableComponent.new(
        entity: @group,
        transfers: @group.consolidated_transfers(depth: 0),
        heading: "Directly Connected to #{@group.name}",
        summarise_for: Group.summarise_for(@group)
      )
    %>
</div>




<%= bar_chart(@data) %>