config/routes.rb
require 'sidekiq/web' # require the web UI

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Flipper::UI.app(Flipper) => '/flipper'
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Prettytodo::Engine => '/prettytodo' if Rails.env.development?

  get 'groups/page=:page' => 'groups#index'
  get 'people/page=:page' => 'people#index'
  get 'transfers/page=:page' => 'transfers#index'

  get 'groups/group_people/:group_id/page=:page' => 'groups#group_people'
  get 'groups/affiliated_groups/:group_id/page=:page' => 'groups#affiliated_groups'
  get 'groups/money_summary/:group_id' => 'groups#money_summary'
  get 'groups/:id/reload' => 'groups#reload'

  get 'people/:id/network_graph' => 'inertia#network_graph_person'
  get 'groups/:id/network_graph' => 'inertia#network_graph_group'

  get 'search' => 'search#index'
  get '/home/suggestions' => 'home#suggestions'

  get '/post_to_socials' => 'home#post_to_socials'              # Random
  get '/people/:id/post_to_socials' => 'people#post_to_socials' # Person

  get '/people/:id/reload' => 'people#reload'
  get '/tradingnames/:id' => 'trading_names#show'

  resources :transfers
  resources :groups
  resources :people

  # todo: remove these
  resources :lazy_load_groups
  resources :lazy_load_people
  resources :lazy_load_transfers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/home/todo' => 'home#todo'
  get '/todo' => 'home#todo'

  get '/home/index' => 'home#index'
  get '/about' => 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'search#index'

  # # Add a custom POST route for Memberships
  post '/admin/memberships/general_upload_action', to: 'admin/memberships#general_upload_action', as: :general_upload_action_admin_memberships
  post '/admin/memberships/ministries_upload_action', to: 'admin/memberships#ministries_upload_action', as: :ministries_upload_action_admin_memberships
  post '/admin/groups/perform_merge', to: 'admin/groups#perform_merge'
  post '/admin/people/ingest_linkedin', to: 'admin/people#ingest_linkedin'
end

app/models/group.rb
class Group < ApplicationRecord
  include TransferMethods
  include NodeMethods
  include CachedMethods

  include PgSearch::Model
  multisearchable against: [:name]

  lazy_columns :cached_data

  MAJOR_POLITICAL_GROUPS = ['Australian Labor Party', 'Liberal / National Coalition', 'The Greens'].freeze

  NAMES = OpenStruct.new(
            coalition: OpenStruct.new(
              federal: 'The Coalition (Federal)',
              nsw: 'The Coalition (NSW)',
              sa: 'The Coalition (SA)',
              vic: 'The Coalition (VIC)',
              tas: 'The Coalition (TAS)',
              wa: 'The Coalition (WA)',
              act: 'The Coalition (ACT)'
            ),
            liberals: OpenStruct.new(
              federal: 'Liberals (Federal)',
              nsw: 'Liberals (NSW)',
              qld: 'Liberal National Party (QLD)',
              sa: 'Liberals (SA)',
              vic: 'Liberals (VIC)',
              tas: 'Liberals (TAS)',
              wa: 'Liberals (WA)',
              act: 'Liberals (ACT)',
              nt: 'Country Liberal Party (NT)'
            ),
            nationals: OpenStruct.new(
              federal: 'Nationals (Federal)',
              nsw: 'Nationals (NSW)',
              qld: 'Liberal National Party (QLD)',
              sa: 'Nationals (SA)',
              vic: 'Nationals (VIC)',
              tas: 'Nationals (TAS)',
              wa: 'Nationals (WA)',
              act: 'Nationals (ACT)',
              nt: 'Country Liberal Party (NT)'
            ),
            labor: OpenStruct.new(
              federal: 'ALP (Federal)',
              nsw: 'ALP (NSW)',
              qld: 'ALP (QLD)',
              sa: 'ALP (SA)',
              vic: 'ALP (VIC)',
              tas: 'ALP (TAS)',
              wa: 'ALP (WA)',
              act: 'ALP (ACT)',
              nt: 'ALP (NT)'
            ),
            greens: OpenStruct.new(
              federal: 'The Greens (Federal)',
              nsw: 'The Greens (NSW)',
              qld: 'The Greens (QLD)',
              sa: 'The Greens (SA)',
              vic: 'The Greens (VIC)',
              tas: 'The Greens (TAS)',
              wa: 'The Greens (WA)',
              act: 'The Greens (ACT)',
              nt: 'The Greens (NT)'
            )
          )

  has_many :trading_names, as: :owner, dependent: :destroy
  has_many :leadership_websites, dependent: :destroy

  # TODO: memberships are only working on one direction, need to fix this
  # affiliated groups are not being followed from child to parent to other child
  has_many :memberships, dependent: :destroy
  has_many :people, through: :memberships, source: :member, source_type: 'Person'
  has_many :groups, through: :memberships, source: :member, source_type: 'Group' # these are the groups that _belong_ to _this_ group
  # these are a bit weird, hence the transfers method below
  has_many :outgoing_transfers, class_name: 'Transfer', as: :giver, dependent: :destroy
  has_many :incoming_transfers, class_name: 'Transfer', as: :taker, dependent: :destroy

  validates :name, uniqueness: { case_sensitive: false }
  validates :business_number, uniqueness: { case_sensitive: false }, allow_nil: true

  accepts_nested_attributes_for :memberships, allow_destroy: true

  normalizes :business_number, with: ->(bn) { bn.presence }
  normalizes :business_number, with: ->(bn) { bn.presence&.gsub(/\D/, '') }

  # scopes
  scope :major_political_tags, -> do
    where(type: 'Tag').where(name: MAJOR_POLITICAL_GROUPS).order(:name)
  end
  scope :other_tags, -> do
    where(type: 'Tag').where.not(name: MAJOR_POLITICAL_GROUPS).order(:name)
  end

  scope :political_parties, -> do
    where(
      id: Membership.joins(:group)
                    .where(groups: { type: 'Tag', name: MAJOR_POLITICAL_GROUPS })
                    .select(:member_id)
    )
  end

  scope :with_business_number, -> { where.not(business_number: [nil, '']) }

  scope :can_refresh, -> { where(last_refreshed: nil).or(where(last_refreshed: ..6.months.ago)) }

  scope :nodes_count_expired, -> { where(nodes_count_cached_at: ..8.days.ago).or(where(nodes_count_cached: nil)) }
  scope :nodes_count_soon_expired, -> { where(nodes_count_cached_at: ..4.days.ago).or(where(nodes_count_cached: nil)) }

  scope :orphans, -> {
    # Groups with no members and no transfers. They may be children of parent groups
    left_outer_joins(:memberships, :incoming_transfers, :outgoing_transfers)
      .where(memberships: { id: nil })
      .where(incoming_transfers: { id: nil })
      .where(outgoing_transfers: { id: nil })
      .distinct
  }

  # Scope: has at least one person
  scope :with_people, -> {
    joins(:people).distinct
  }
  # Scope: has at least one group (as member)
  scope :with_groups, -> {
    joins(:groups).distinct
  }

  scope :created_since, ->(since) {
    where(created_at: since..Time.current)
  }

  # Scope: groups that are members of the lobbyists tag
  scope :lobbyist_groups, -> {
    lobbyist_tag = Group.lobbyists_tag
    joins("INNER JOIN memberships ON memberships.member_id = groups.id AND memberships.member_type = 'Group'")
      .where('memberships.group_id = ?', lobbyist_tag.id)
      .distinct
  }

  def parent_groups
    Group.joins(:memberships).where(memberships: { member: self, member_type: 'Group' }).where.not(id: self.id)
  end

  def nodes
    people + affiliated_groups
  end

  def affiliated_groups
    parent_groups + groups
  end

  def less_level
    # only called from a disused section in FileIngestor
    # TODO: Potentially useless code
    name.gsub(/(Federal|NSW|VIC|SA|WA|TAS|ACT|NT)/, '')
        .delete('(')
        .delete(')')
        .strip
  end

  def state
    name.match(/(NSW|VIC|QLD|SA|WA|TAS|ACT|NT)/).to_s
  end

  def self.summarise_for(group = nil)
    major_groupings = %i(coalition nationals labor green liberals)
    states = %i[federal nsw vic qld sa wa nt act tas]

    list = major_groupings.map do |major_group|
      states.map do |state|
        NAMES.send(major_group).send(state) if NAMES.send(major_group)
      end
    end

    if group.present?
      list.flatten.compact.uniq - [group.name]
    else
      list.flatten.compact.uniq
    end
  end

  def is_tag?
    type == 'Tag'
  end

  def is_group? = true
  def is_person? = false

  def display_name
    return "#{name} (#{business_number})" if business_number.present?

    name
  end

  def add_to_tag(tag_group: nil, tag_name: nil)
    raise ArgumentError, 'Either tag_group or tag_name must be provided' if tag_group.blank? && tag_name.blank?
    return if self.is_tag?

    tag_group ||= Group.find_or_create_by!(name: tag_name, type: 'Tag')
    Tag::AddGroupToTag.call(tag: tag_group, group: self)
  end

  def self.all_named_parties
    NAMES.to_h.keys.map do |key|
      NAMES.send(key).to_h.values
    end.flatten.uniq
  end

  def self.find_by_name_i(name)
    Group.where('LOWER(name) = ?', name.downcase).first
  end

  def self.lobbyists_tag
    Group.find_by(name: 'Lobbyists')
  end

  def self.client_of_lobbyists_tag
    Group.find_by(name: 'Client of Lobbyists')
  end

  def self.government_department_tag
    Group.find_by(name: 'Government Departments (AU, Federal & State)')
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  rate_limit to: Constants::CONTROLLER_RATE_LIMIT, within: 1.minute, with: -> { redirect_to search_path, alert: 'Too many requests, Please try in a minute...' } # unless Rails.env.test? || Rails.env.development?

  include Constants

  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :set_page, only: %i[ index ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  def index
    groups = Group.order(:name).limit(page_size).offset(paginate_offset).to_a
    pages = (Group.count.to_f / page_size).ceil

    render Groups::IndexView.new(groups:, page: @page, pages:)
  end

  def show
    if @group.cache_fresh?
      render Groups::ShowView.new(group: @group)
    else
      BuildGroupCachedDataJob.perform_async(@group.id)
      render Common::PleaseRefreshLater.new
    end
  end

  def reload
    @group = Group.find(params[:id])
    BuildGroupCachedDataJob.perform_async(@group.id)

    render Groups::ShowView.new(group: @group.reload)
  end

  def affiliated_groups
    @group = Group.find(params[:group_id])
    @page = params[:page].to_i

    render Groups::AffiliatedGroups.new(group: @group)
  end

  def money_summary
    render Common::MoneySummary.new(entity: Group.find(params[:group_id]))
  end

  def group_people
    # This action used to have pagination. TODO: re-add pagination into the new format?
    group = Group.find(params[:group_id])
    page = params[:page].to_i
    pages = (group.people.count.to_f / page_size).ceil

    people = group.cached
                  .direct_connections
                  .filter { |c| c['klass'] == 'Person' }
                  .sort_by { |c| c['name'] }

    #  passing an array of hashes to the view
    render Groups::PeopleTable.new(people:, exclude_group: group, page:, pages:)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  def set_page
    @page = (params[:page] || 0).to_i
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, memberships_attributes: [:id, :title, :start_date, :end_date, :_destroy])
  end

  def update_group(group)
    people_ids = group_params['people_ids'].compact_blank.map(&:to_i)

    people_ids.each do |id|
      person = Person.find(id)
      person.groups << group unless person.groups.include?(group)
    end

    group
  end

  def page_size
    return 250

    @page_size ||= Constants::PAGE_LIMIT
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/admin/groups/merge_with.html.erb
<h3>The Group: <%= @current_group.name %> will be merged with another group. This action cannot be undone. The second group will be destroyed</h3>

<h4><%= link_to "Return to main view", "/groups/#{@current_group.id}" %></h4>

<div style="margin-top: 20px; padding: 15px; border: 2px solid #28a745; background-color: #e8f5e9;">
  <h3>Search for Group</h3>
  <%= form_with url: search_groups_admin_group_path(@current_group), method: :post, local: true do |form| %>
    <div>
      <%= form.label :query, "Search by name:" %><br>
      <%= form.text_field :query, value: @search_query, placeholder: "Enter group name..." %>
      <%= form.hidden_field :current_group_id, value: @current_group.id %>
    </div>
    <div style="margin-top: 10px;">
      <%= form.submit "Search" %>
    </div>
  <% end %>
</div>

<% if @search_results.present? %>
  <div style="margin-top: 20px; padding: 15px; border: 2px solid #6c757d; background-color: #f8f9fa;">
    <h3>Search Results</h3>
    <% @search_results.each do |result| %>
      <div style="padding: 10px; margin: 5px 0; border: 1px solid #dee2e6; background-color: white;">
        <strong><%= result.searchable.name %></strong> (ID: <%= result.searchable_id %>) (ABN: <%= result.searchable.business_number %>)<br>
        <%= form_with url: preview_merge_admin_group_path(@current_group), method: :post, local: true, style: "display: inline; margin-left: 10px;" do |form| %>
          <%= form.hidden_field :merge_with_group_id, value: result.searchable_id %>
          <%= form.hidden_field :current_group_id, value: @current_group.id %>
          <%= form.submit "Select This Group", style: "padding: 5px 10px;" %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<div style="margin-top: 20px; padding: 15px; border: 2px solid #007bff; background-color: #e7f3ff;">
  <h3>Group ID</h3>
  <%= form_with url: preview_merge_admin_group_path(@current_group), method: :post, local: true do |form| %>
    <div>
      <%= form.label :merge_with_group_id, "Enter group ID to merge with:" %><br>
      <%= form.number_field :merge_with_group_id, value: @merge_with_group_id, style: "width: 120px;" %>
      <%= form.hidden_field :current_group_id, value: @current_group.id %>
    </div>
    <div style="margin-top: 10px;">
      <%= form.submit "Preview Group" %>
    </div>
  <% end %>
</div>

<% if @merge_with_group.present? %>
  <div style="margin-top: 20px; padding: 15px; border: 2px solid #ffcc00; background-color: #fff9e6;">
    <h3>Confirmation</h3>
    <p><strong>Current Group:</strong> <%= @current_group.name %> (ID: <%= @current_group.id %>)</p>
    <p><strong>Will be merged into:</strong> <%= @merge_with_group.name %> (ID: <%= @merge_with_group.id %>)</p>
    <p style="color: #cc0000; font-weight: bold;">This action cannot be undone!</p>

    <%= form_with url: perform_merge_admin_group_path(@current_group), method: :post, local: true do |form| %>
      <%= form.hidden_field :merge_with_group_id, value: @merge_with_group.id %>
      <%= form.hidden_field :current_group_id, value: @current_group.id %>
      <div>
        <%= form.submit "Confirm Merge", data: { confirm: "Are you absolutely sure you want to merge #{@current_group.name} into #{@merge_with_group.name}?" } %>
      </div>
    <% end %>
  </div>
<% end %>